import {
  Leaf,
  Rss,
  PlusCircle,
  FileText,
  BookOpen,
  ShieldCheck,
  Clock,
  Calendar,
  Sliders,
  Trophy,
  Medal,
  Sparkles,
  History,
  GraduationCap,
  BookMarked,
  School,
  Layers,
  Briefcase,
  UserCheck,
  FolderKanban,
  UserPlus,
  Archive,
  Settings,
  Users,
} from 'lucide-react'

/**
 * Configuración declarativa de rutas y navegación con RBAC para Eco-Guardianes
 * Cada grupo y sub-item cuenta con su lista estricta de 'allowedRoles'.
 */
export const navigationConfig = [
  {
    id: 'eco-module',
    title: 'Módulo Ecológico',
    icon: Leaf,
    allowedRoles: ['ADMIN', 'COORDINATOR', 'TEACHER', 'STUDENT'],
    items: [
      {
        id: 'feed',
        label: 'Feed General',
        path: '/feed',
        icon: Rss,
        allowedRoles: ['ADMIN', 'COORDINATOR', 'TEACHER', 'STUDENT'],
      },
      {
        id: 'new-post',
        label: 'Subir Evidencia',
        path: '/posts/new',
        icon: PlusCircle,
        allowedRoles: ['STUDENT', 'ADMIN'],
      },
      {
        id: 'my-posts',
        label: 'Mis Publicaciones',
        path: '/posts/my-posts',
        icon: FileText,
        allowedRoles: ['STUDENT', 'ADMIN'],
      },
      {
        id: 'rubric',
        label: 'Rúbrica Oficial',
        path: '/rubric',
        icon: BookOpen,
        allowedRoles: ['ADMIN', 'COORDINATOR', 'TEACHER', 'STUDENT'],
      },
    ],
  },
  {
    id: 'turns-module',
    title: 'Turnos y Guardianes',
    icon: ShieldCheck,
    allowedRoles: ['ADMIN', 'COORDINATOR', 'TEACHER', 'STUDENT'],
    items: [
      {
        id: 'current-turn',
        label: 'Turno de la Semana',
        path: '/turns/current',
        icon: Clock,
        allowedRoles: ['ADMIN', 'COORDINATOR', 'TEACHER', 'STUDENT'],
      },
      {
        id: 'calendar-turns',
        label: 'Calendario de Rondas',
        path: '/turns/calendar',
        icon: Calendar,
        allowedRoles: ['ADMIN', 'COORDINATOR', 'TEACHER', 'STUDENT'],
      },
      {
        id: 'manage-turns',
        label: 'Gestión de Turnos',
        path: '/turns/manage',
        icon: Sliders,
        allowedRoles: ['ADMIN', 'COORDINATOR'],
      },
    ],
  },
  {
    id: 'leaderboards-module',
    title: 'Leaderboards y Podios',
    icon: Trophy,
    allowedRoles: ['ADMIN', 'COORDINATOR', 'TEACHER', 'STUDENT'],
    items: [
      {
        id: 'collective-ranking',
        label: 'Ranking de Secciones',
        path: '/rankings/collective',
        icon: Medal,
        allowedRoles: ['ADMIN', 'COORDINATOR', 'TEACHER', 'STUDENT'],
      },
      {
        id: 'individual-ranking',
        label: 'Top Eco-Aura',
        path: '/rankings/individual',
        icon: Sparkles,
        allowedRoles: ['ADMIN', 'COORDINATOR', 'TEACHER', 'STUDENT'],
      },
      {
        id: 'ranking-history',
        label: 'Historial de Podios',
        path: '/rankings/history',
        icon: History,
        allowedRoles: ['ADMIN', 'COORDINATOR', 'TEACHER', 'STUDENT'],
      },
    ],
  },
  {
    id: 'teacher-module',
    title: 'Panel Docente',
    icon: GraduationCap,
    allowedRoles: ['TEACHER', 'ADMIN', 'COORDINATOR'],
    items: [
      {
        id: 'my-classes',
        label: 'Mis Clases Asignadas',
        path: '/teacher/classes',
        icon: BookMarked,
        allowedRoles: ['TEACHER', 'ADMIN', 'COORDINATOR'],
      },
    ],
  },
  {
    id: 'admin-academic-module',
    title: 'Administración Académica',
    icon: School,
    allowedRoles: ['ADMIN', 'COORDINATOR'],
    items: [
      {
        id: 'levels-sections',
        label: 'Niveles y Secciones',
        path: '/admin/levels',
        icon: Layers,
        allowedRoles: ['ADMIN', 'COORDINATOR'],
      },
      {
        id: 'careers',
        label: 'Carreras Técnicas',
        path: '/admin/careers',
        icon: Briefcase,
        allowedRoles: ['ADMIN', 'COORDINATOR'],
      },
      {
        id: 'coordinators',
        label: 'Coordinaciones',
        path: '/admin/coordinators',
        icon: UserCheck,
        allowedRoles: ['ADMIN'],
      },
      {
        id: 'classes-workshops',
        label: 'Clases y Talleres',
        path: '/admin/classes',
        icon: FolderKanban,
        allowedRoles: ['ADMIN', 'COORDINATOR'],
      },
      {
        id: 'enrollment',
        label: 'Matrícula de Alumnos',
        path: '/admin/enrollment',
        icon: UserPlus,
        allowedRoles: ['ADMIN', 'COORDINATOR'],
      },
      {
        id: 'close-bimester',
        label: 'Cierre de Bimestre',
        path: '/admin/close-bimester',
        icon: Archive,
        allowedRoles: ['ADMIN', 'COORDINATOR'],
      },
    ],
  },
  {
    id: 'system-module',
    title: 'Sistema',
    icon: Settings,
    allowedRoles: ['ADMIN', 'COORDINATOR'],
    items: [
      {
        id: 'users',
        label: 'Usuarios',
        path: '/admin/users',
        icon: Users,
        allowedRoles: ['ADMIN', 'COORDINATOR'],
      },
    ],
  },
]
